### ISSUE TITLE
asynchronous UDF functionality  - UDAs, wrapping and registration

### ISSUE THREAD

**Issue by Laeeth** [kaleidicassociates/excel-d#4] opened 2017-03-26 09:14 UTC
https://msdn.microsoft.com/en-us/library/office/ff796219(v=office.14).aspx

**Comment by Laeeth** [comment] 2017-04-20 23:05
in particular this is useful for example for long-running get/put operations.  we don't want to block excel whilst the data access operation is running.  much better to return immediately and update a status when remote server returns it.

also useful for long-running calculations

**Comment by atilaneves** [comment] 2017-12-21 19:42
Duplicate of #35

**Closed by atilaneves** 2017-12-21 19:42 UTC
Labels: enhancement
